seed: 2025

input:
  dataset_path: data/dataset_v2.csv

columns:
  target: MedHouseVal
  drop: []

preprocess:
  test_size: 0.2
  impute_strategy_num: median
  impute_strategy_cat: most_frequent
  one_hot_drop: first
  scale_numeric: true

models:
  - name: linear
    type: LinearRegression
    params: {}
  - name: rf
    type: RandomForestRegressor
    params:
      n_estimators: 250
      max_depth: 1
      random_state: 2025
      n_jobs: -1
  - name: gbr
    type: GradientBoostingRegressor
    params:
      n_estimators: 100
      learning_rate: 0.05
      max_depth: 3
      random_state: 2025

metrics:
  - r2
  - rmse
  - mae

output:
  X_train: data/splits/X_train.parquet
  X_test: data/splits/X_test.parquet
  y_train: data/splits/y_train.parquet
  y_test: data/splits/y_test.parquet
  processed: data/processed/processed.parquet
  preds: artifacts/preds.csv
  best_model: models/best_model.joblib
  metrics_global: artifacts/metrics.json
  metrics_by_model: artifacts/metrics_by_model.json


